import utils
# # Container 1A (mm and kg)
# CONTAINER_WIDTH = 2330
# CONTAINER_HEIGHT = 2200
# CONTAINER_DEPTH = 12000
# CONTAINER_LOAD = 26480
# Container SMALL (mm and kg)
CONTAINER_WIDTH = 1500 # x axis
CONTAINER_HEIGHT = 2000 # z axis
CONTAINER_DEPTH = 12000 # y axis
CONTAINER_LOAD = 26480

# Pallet EO (mm and kg)
PALLET_WIDTH = 1260 # x axis
PALLET_DEPTH = 1060 # y axis
PALLET_HEIGHT = CONTAINER_HEIGHT - 200  # z axis 200 is the height of the upper sensor
PALLET_LOAD = 2490
PALLET_DIMS = utils.Dimension(PALLET_WIDTH, PALLET_DEPTH, PALLET_HEIGHT, PALLET_LOAD)
# # Pallet EUR 1 (mm and kg)
# PALLET_WIDTH = 1200
# PALLET_DEPTH = 800
# PALLET_HEIGHT = CONTAINER_HEIGHT - 145  # 145 is the height of the pallet itself
# PALLET_LOAD = 2490
# PALLET_DIMS = utils.Dimension(PALLET_WIDTH, PALLET_DEPTH, PALLET_HEIGHT, PALLET_LOAD)
# Product dimension ranges (mm and kg)
NUM_PRODUCTS = int(1e4)
MIN_PRODUCT_WIDTH = 50
MAX_PRODUCT_WIDTH = PALLET_WIDTH
MIN_PRODUCT_DEPTH = 50
MAX_PRODUCT_DEPTH = PALLET_DEPTH
MIN_PRODUCT_HEIGHT = 50
MAX_PRODUCT_HEIGHT = PALLET_HEIGHT
MIN_PRODUCT_WEIGHT = 2
MAX_PRODUCT_WEIGHT = PALLET_LOAD

# Numpy
RANDOM_SEED = 42
